###### simulation studies ######


################################################################
######### function for generating simulation data ##############
################################################################


############# irregular data ####################

generate_multinom = function(n){
  # generate 3 by n category multinomial data
  # 3 is the num of categories
  # n is num of ovservations
  
  # generate prob for category1
  x1 = seq(1,n/2,1)
  tmp1 = 0.0002*x1^2
  prob1_1 = abs(tmp1 + rnorm(n/2,0,0.01))
  x2 = seq((n/2+1),n,1)
  tmp2 = 1.25-0.01*x2
  prob1_2 = abs(tmp2+rnorm(n/2,0,0.01))
  prob1 =cbind(t(as.matrix(prob1_1)),t(as.matrix(prob1_2)))
  
  # genrate prob for category2
  x = seq(1,n,1)
  tmp3 = rep(0.05,n)
  prob2 = t(as.matrix(tmp3 + rnorm(n,0,0.01)))
  
  P = matrix(NA,3,n)
  y = matrix(NA,3,n)
  
  for(i in 1:n){
    P[1,i] = prob1[1,i]
    P[2,i] = prob2[1,i]
    P[3,i] = 1-P[1,i] - P[2,i]
    y[,i] = rmultinom(n=1,size=1,prob=P[,i])
  } 
  
  # return the probability matrix and the data
  return(list(P,y))
}

########### show the data pattern by plot ################3
n = 100
test_all = generate_multinom(n)

### probability 
test_p = test_all[[1]]
test_ct1_p = cbind(seq(1,n,1),rep(1,n),test_p[1,])
test_ct2_p = cbind(seq(1,n,1),rep(2,n),test_p[2,])
test_ct3_p = cbind(seq(1,n,1),rep(3,n),test_p[3,])
test_p = rbind(test_ct1_p,test_ct2_p,test_ct3_p)
test_p = as.data.frame(test_p)
names(test_p) = c('x','category','probability')
test_p$category = as.factor(test_p$category)
# str(test_p)

library(ggplot2)
plt_p = ggplot(data=test_p,aes(x=x,y=probability))
plt_p = plt_p+geom_line(aes(color=category),alpha=1/2,size=2)
plt_p = plt_p+labs(title="Probability Generated by Function 'generate'")
plt_p = plt_p+labs(x='Predictor Sequence')+labs(y='Probability')
plt_p

### data
test_dat = test_all[[2]]
test_ct1_dat = cbind(seq(1,n,1),rep(1,n),test_dat[1,])
test_ct2_dat = cbind(seq(1,n,1),rep(2,n),test_dat[2,])
test_ct3_dat = cbind(seq(1,n,1),rep(3,n),test_dat[3,])
test_dat = rbind(test_ct1_dat,test_ct2_dat,test_ct3_dat)
test_dat = as.data.frame(test_dat)
names(test_dat) = c('x','category','outcome')
test_dat$category = as.factor(test_dat$category)
# str(test_dat)

plt_dat = ggplot(data=test_dat,aes(x=x,y=outcome))
plt_dat = plt_dat+geom_point(color='steel blue',alpha=1/2,size=5)
plt_dat = plt_dat+facet_grid(.~category)
plt_dat = plt_dat+labs(title="Data Generated by Function 'generate'")
plt_dat = plt_dat+labs(x='Predictor Sequence')+labs(y='Outcome')
plt_dat

########## linear data ##############################

generate_multinom_linear= function(n){
  beta = rbind(c(0.6,0.002),c(0.7,-0.003),c(0,0))
  x = rbind(rep(1,n),seq(1,n,1))
  o = exp(beta%*%x)
  p = matrix(NA,3,100)
  y = matrix(NA,3,100)
  for(i in 1:100){
    p[1,i] = o[1,i]/sum(o[,i])
    p[2,i] = o[2,i]/sum(o[,i])
    p[3,i] = 1-p[1,i] - p[2,i]
    y[,i] = rmultinom(1,1,p[,i])
  }
  return(list(p,y))
}

########### show the data pattern by plot #############
n = 100
test_all_l = generate_multinom_linear(n)

### probability 
test_p_l = test_all_l[[1]]
test_ct1_p_l = cbind(seq(1,n,1),rep(1,n),test_p_l[1,])
test_ct2_p_l = cbind(seq(1,n,1),rep(2,n),test_p_l[2,])
test_ct3_p_l = cbind(seq(1,n,1),rep(3,n),test_p_l[3,])
test_p_l = rbind(test_ct1_p_l,test_ct2_p_l,test_ct3_p_l)
test_p_l = as.data.frame(test_p_l)
names(test_p_l) = c('x','category','probability')
test_p_l$category = as.factor(test_p_l$category)
str(test_p_l)

library(ggplot2)
plt_p_l = ggplot(data=test_p_l,aes(x=x,y=probability))
plt_p_l = plt_p_l+geom_line(aes(color=category),alpha=1/2,size=2)
plt_p_l = plt_p_l+labs(title="Probability Generated by Function 'generate_linear'")
plt_p_l = plt_p_l+labs(x='Predictor Sequence')+labs(y='Probability')
plt_p_l





#############################################################
############# function for getting error ####################
#############################################################

get_error = function(y1,y2){
  # y1 and y2 needs to have same dimension
  error = 0
  n1 = dim(y1)[1]
  n2 = dim(y1)[2]
  
  for(i in 1:n1){
    for(j in 1:n2){
      error = error + abs(y1[i,j] - y2[i,j])
    }
  }

  return(error/(n1*n2))
}

###############################################################
############# function for simiulation ########################
###############################################################

########### irregular data ##################

#### nonparametric ####
sim_nonparametric_multinom = function(N,M,K,reps=1e2){
  Err = rep(0,reps)
  for(r in 1:reps){
    f = generate_multinom(N)
    P = f[[1]] 
    Y = f[[2]]
    out = manysteps_multinom(y=Y,m=M,k=K,R=1e3,ct=3)
    if(length(out) == 1){
      Err[r] = 0
    }
    else{
      Err[r] = get_error(out[[2]],P)
    }
  }
  
  c = 0
  for(r in 1:reps){
    if(Err[r] == 0){
      c = c+1
    }
  }
  return(sum(Err)/(reps-c))
}


#### multilogit model ####
sim_multilogit = function(n,reps=1e3){
  Err = rep(0,reps)
  c = 0
  for(r in 1:reps){
    o = generate_multinom(n)
    p = o[[1]]
    y = o[[2]]
    
    # prepare data
    response = rep(0,n)
    for(i in 1:n){
      c = 0
      for(j in 1:3){
        if(y[j,i] == 1)
          c = j
      }
      response[i] = c
    }
    
    # data
    response = as.factor(response)
    x1 = seq(1,n,1)
    x0 = rep(1,n)
    x = rbind(x0,x1)
    
    # train model
    library(nnet)
    mod = multinom(response~x1)
    betahat.matrix = rbind(coef(mod),0)
    
    if(dim(betahat.matrix)[1] == 3){
      # est p
      est.prob = matrix(NA,3,n)
      foo1 = exp(betahat.matrix%*%x)
      foo2 = colSums(foo1)
      for(i in 1:3){
        for(j in 1:n){
          est.prob[i,j] = foo1[i,j]/foo2[j]
        }
      }
      Err[r] = get_error_multinom(y1=p,y2=est.prob)
    }
    else{
      Err[r] = 0
      c = c+1
    }
    
    }
    
    return(sum(Err)/(reps-c))
}



sim_multilogit_square = function(n,reps=1e3){
  Err = rep(0,reps)
  c = 0
  for(r in 1:reps){
    o = generate_multinom(n)
    p = o[[1]]
    y = o[[2]]
    
    # prepare data
    response = rep(0,n)
    for(i in 1:n){
      c = 0
      for(j in 1:3){
        if(y[j,i] == 1)
          c = j
      }
      response[i] = c
    }
    
    # data
    response = as.factor(response)
    x1 = seq(1,n,1)
    x0 = rep(1,n)
    x2 = x1^2
    x = rbind(x0,x1,x2)
    
    # train model
    library(nnet)
    mod = multinom(response~x1+x2)
    betahat.matrix = rbind(coef(mod),0)
    
    if(dim(betahat.matrix)[1] == 3){
      # est p
      est.prob = matrix(NA,3,n)
      foo1 = exp(betahat.matrix%*%x)
      foo2 = colSums(foo1)
      for(i in 1:3){
        for(j in 1:n){
          est.prob[i,j] = foo1[i,j]/foo2[j]
        }
      }
      Err[r] = get_error_multinom(y1=p,y2=est.prob)
    }
    else{
      Err[r] = 0
      c = c+1
    }
    
  }
  
  return(sum(Err)/(reps-c))
}


#### simulate and comparison ####

### simulate multi logit ##
sim_multilogit(n=100,reps=1e3)
sim_multilogit_square(n=100,reps=1e3)

### simulate nonparametric and compare with multi logit ###
## compare different k
# for m = 3
sim_nonparametric_multinom(N=100,M=3,K=13,reps=1e2)
sim_nonparametric_multinom(N=100,M=3,K=10,reps=1e2)
sim_nonparametric_multinom(N=100,M=3,K=8,reps=1e2)
sim_nonparametric_multinom(N=100,M=3,K=5,reps=1e2)
sim_nonparametric_multinom(N=100,M=3,K=3,reps=1e2)

# for m = 5
sim_nonparametric_multinom(N=100,M=5,K=13,reps=1e2)
sim_nonparametric_multinom(N=100,M=5,K=10,reps=1e2)
sim_nonparametric_multinom(N=100,M=5,K=8,reps=1e2)
sim_nonparametric_multinom(N=100,M=5,K=5,reps=1e2)
sim_nonparametric_multinom(N=100,M=5,K=3,reps=1e2)

# for m = 7
sim_nonparametric_multinom(N=100,M=7,K=13,reps=1e2)
sim_nonparametric_multinom(N=100,M=7,K=10,reps=1e2)
sim_nonparametric_multinom(N=100,M=7,K=8,reps=1e2)
sim_nonparametric_multinom(N=100,M=7,K=5,reps=1e2)
sim_nonparametric_multinom(N=100,M=7,K=3,reps=1e2)





########### linear data ##################

#### nonparametric ####
library(nnet)
sim_multilogit_linear = function(n,reps = 1e3){
  Err = rep(0,reps)
  c = 0
  for(r in 1:reps){
    out = generate_multinom_linear(n)
    p = out[[1]]
    y = out[[2]]
    
    # prepare data
    response = rep(0,n)
    for(i in 1:n){
      c = 0
      for(j in 1:3){
        if(y[j,i] == 1)
          c = j
      }
      response[i] = c
    }
    
    response = as.factor(response)
    predictor = seq(1,n)
    m = multinom(response~predictor)
    beta = rbind(coef(m),0)
    x = rbind(rep(1,n),seq(1,n,1))
    foo = exp(beta%*%x)
    est.prob= matrix(NA,3,100)
    for(i in 1:100){
      est.prob[1,i] = foo[1,i]/sum(foo[,i])
      est.prob[2,i] = foo[2,i]/sum(foo[,i])
      est.prob[3,i] = 1-est.prob[1,i] - est.prob[2,i]
    }
    
    if(dim(est.prob)[1] == 3){
      Err[r] = get_error(y1=p,y2=est.prob)
    }
    else{
      Err[r] = 0
      c = c+1
    }
    
  }
  
  return(sum(Err)/(reps-c))
}

#### nonparametric ####

sim_nonparametric_multinom_linear = function(N,M,K,reps=1e2){
  Err = rep(0,reps)
  for(r in 1:reps){
    f = generate_multinom_linear(N)
    P = f[[1]] 
    Y = f[[2]]
    out = manysteps_multinom(y=Y,m=M,k=K,R=1e3,ct=3)
    if(length(out) == 1){
      Err[r] = 0
    }
    else{
      Err[r] = get_error(out[[2]],P)
    }
  }
  
  c = 0
  for(i in 1:reps){
    if(Err[i] == 0){
      c = c+1
    }
  }
  return(sum(Err)/(reps-c))
}

#### simulate and comparison ####

### simulate multi logit ##

sim_multilogit_linear(n=100,reps=1e3)

### simulate nonparametric and compare with multi logit ###

# for m = 3
sim_nonparametric_multinom_linear(N=100,M=3,K=13,reps=1e2)
sim_nonparametric_multinom_linear(N=100,M=3,K=10,reps=1e2)
sim_nonparametric_multinom_linear(N=100,M=3,K=8,reps=1e2)
sim_nonparametric_multinom_linear(N=100,M=3,K=5,reps=1e2)
sim_nonparametric_multinom_linear(N=100,M=3,K=3,reps=1e2)

# for m = 5
sim_nonparametric_multinom_linear(N=100,M=5,K=13,reps=1e2)
sim_nonparametric_multinom_linear(N=100,M=5,K=10,reps=1e2)
sim_nonparametric_multinom_linear(N=100,M=5,K=8,reps=1e2)
sim_nonparametric_multinom_linear(N=100,M=5,K=5,reps=1e2)
sim_nonparametric_multinom_linear(N=100,M=5,K=3,reps=1e2)

# for m = 7
sim_nonparametric_multinom_linear(N=100,M=7,K=13,reps=1e2)
sim_nonparametric_multinom_linear(N=100,M=7,K=10,reps=1e2)
sim_nonparametric_multinom_linear(N=100,M=7,K=8,reps=1e2)
sim_nonparametric_multinom_linear(N=100,M=7,K=5,reps=1e2)
sim_nonparametric_multinom_linear(N=100,M=7,K=3,reps=1e2)